Repository Ritikverma323/computer-science-blogs, pull requests merged in 2025-10, with the labels that each got.

#20 reactjs-with-nextjs-setup : React and Next Js setup.
  .gitignore
  README.md
  eslint.config.mjs
  next.config.ts
  package-lock.json
  package.json
  postcss.config.mjs
  public/file.svg
  public/globe.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  tsconfig.json
Labels: good first issue, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted

#25 Enhanced Dark Mode: Advanced Theme System with Preference Sync & Smooth Animations
  css/style.css
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted

#26 add_categories_section: add_categories_section.
  src/app/category/[slug]/page.tsx
  src/app/category/page.tsx
  src/app/page.tsx
  src/app/post/[id]/page.tsx
  src/components/BlogLayout.tsx
  src/components/CategoryList.tsx
  src/components/Header.tsx
  src/components/PostCard.tsx
  src/data/categories.ts
  src/data/posts.ts
Labels: good first issue, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted

#28 searchbar: Added search bar feature.
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/SearchBar.tsx
  src/styles/globals.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#44 added a page of visitors count
  .vscode/settings.json
  src/app/api/visitor/route.ts
  src/app/visitors/page.tsx
  src/components/Header.tsx
  src/components/VisitorCount.tsx
  src/data/visitorData.json
  src/lib/visitorUtils.ts
  src/styles/globals.css
Labels: good first issue, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted

#43 Feature/add user comments blog #13
  public/avatars/user1.jpg
  public/avatars/user2.jpg
  public/avatars/user3.jpg
  public/avatars/user4.jpg
  src/app/post/[id]/page.tsx
  src/components/Comments.tsx
  src/data/posts.ts
  src/styles/globals.css
Labels: good first issue, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted

#63 feat:Add a Next.js Modals component. #53
  src/app/page.tsx
  src/components/Modal.tsx
  src/styles/globals.css
Labels: good first issue, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted

#64 [FEATURE] Add Progress Bar for Blog Reading #54
  src/app/post/[id]/page.tsx
  src/components/ReadingProgressBar.tsx
  src/styles/globals.css
Labels: hacktoberfest, hacktoberfest-accepted

#56 Notes/queues data structure
  notes/data-structure/queues.html
Labels: good first issue, hacktoberfest, hacktoberfest2025, hacktoberfest-accepted
